"""Shopping Copilot agent implementation.

The entry point is `agent.py` at the bundle root; this package holds the modules it
orchestrates. Generated by `tools/build_submission.py` from the repository's
`starter/` package -- the only difference is the import paths.
"""
