"""Competition entry point -- exports `Agent` for the official harness.

The implementation lives in `src/`; this file exists so the bundle matches the layout in
`docs/submission_rules.md` ("one Python agent entry file exporting `Agent`"). Generated by
`tools/build_submission.py` -- edit `starter/` and rebuild, never this file.

    from agent import Agent

`src/agent.py` is a byte-for-byte copy of the repository's `starter/agent.py` apart from
its import lines. See README.md for setup, reproduction, and the feasibility disclosure.
"""

from src.agent import Agent

__all__ = ["Agent"]
