"""Build the competition submission bundle, then prove it is the agent we measured.

`docs/submission_rules.md` asks for a packaged entry -- an agent file exporting `Agent`,
its helper modules, a dependency manifest, and setup instructions -- laid out as:

    submission/
      agent.py
      requirements.txt
      README.md
      src/

We cannot simply rename `starter/` into that shape. `evaluator/local_evaluator.py:12`
does `from starter.agent import Agent` and the evaluator is organizer-owned and not
editable, so `starter/` has to stay exactly where it is. The bundle is therefore
*generated* from it:

    py tools/build_submission.py
    py tools/build_submission.py --skip-verify     # build only; for iterating

**The bundle is never hand-edited.** Anything hand-maintained beside the code it mirrors
drifts, and it drifts silently -- you find out when a judge runs it, not when you commit.
Everything here is copied or rewritten from a single source in the repo, so the way to
change the bundle is to change that source and rebuild.

## What verification actually proves

The last check runs the full 200-session evaluation *against the bundled copy* and
requires the result to be **byte-identical** to the committed score of record. That is
stronger than "it imports" and stronger than "it scores 0.912205": the evaluator's output
document carries no timing or environment fields (`evaluator/local_evaluator.py:284-295`),
so it is fully deterministic, and a byte comparison catches a session that moved even when
the aggregate happens to land in the same place. It costs one ~25-40 s run, which is the
entire point of the script.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
STARTER = REPO / "starter"
BUNDLE = REPO / "submission"
REFERENCE = REPO / "results" / "results_after_fieldfactors.json"

# The bundle's two documents, authored in `docs/` so the bundle stays generated.
# `submission_rules.md` requires it to carry setup instructions *and* a report *and* a
# latency/token/cost disclosure -- so the README is setup only and the report gets its own
# file, rather than a judge having to scroll past the method to find the install steps.
DOCUMENTS = {
    "README.md": REPO / "docs" / "submission_setup.md",
    "REPORT.md": REPO / "docs" / "submission_report.md",
}

# Every module in `starter/`. `env_file.py` is never imported by the scored path -- that
# isolation is asserted by tools/verify_llm.py -- but `llm.py` documents it and the WebUI
# uses it, so shipping it keeps the bundle's own docstrings honest at no cost.
MODULES = (
    "__init__.py",
    "agent.py",
    "dense_retrieval.py",
    "dialog_state.py",
    "env_file.py",
    "facets.py",
    "llm.py",
    "ranking.py",
    "retrieval.py",
)

# Rewrite import statements only. A blanket `starter` -> `src` replace would corrupt
# prose: the word appears in docstrings and comments throughout ("Participant starter
# package", "the starter baseline", "starter kit"). The leading `\s*` matters just as
# much -- four of these imports are *inside functions*, indented, and an anchored
# `^from starter` would miss every one of them:
#
#     starter/dialog_state.py:381   from starter import llm as llm_module
#     starter/retrieval.py:252      from starter.dense_retrieval import DenseIndex
#     starter/retrieval.py:467,514  from starter import facets as facets_module
IMPORT_REWRITES = (
    (re.compile(r"^(\s*)from starter import ", re.MULTILINE), r"\1from src import "),
    (re.compile(r"^(\s*)from starter\.(\w+) import ", re.MULTILINE), r"\1from src.\2 import "),
    (re.compile(r"^(\s*)import starter\b", re.MULTILINE), r"\1import src"),
)

# The modules also cross-reference each other by path in their comments -- "see
# starter/llm.py", "starter/agent.py:150". Those paths do not exist in the bundle, so a
# judge following one lands nowhere. Rewrite the *path* form only; it cannot be confused
# with the bare word, which is prose about the starter kit and stays as written. Every
# substitution is within a line, so the `file.py:NNN` line references stay accurate.
PATH_REWRITE = re.compile(r"\bstarter/(\w+)\.py")

ENTRY_POINT = '''"""Competition entry point -- exports `Agent` for the official harness.

The implementation lives in `src/`; this file exists so the bundle matches the layout in
`docs/submission_rules.md` ("one Python agent entry file exporting `Agent`"). Generated by
`tools/build_submission.py` -- edit `starter/` and rebuild, never this file.

    from agent import Agent

`src/agent.py` is a byte-for-byte copy of the repository's `starter/agent.py` apart from
its import lines. See README.md for setup, reproduction, and the feasibility disclosure.
"""

from src.agent import Agent

__all__ = ["Agent"]
'''

SHIM = '''"""Compatibility shim: `from starter.agent import Agent` against the bundle.

The official harness we were given imports the agent by that path
(`evaluator/local_evaluator.py:12`). The bundle's canonical entry point is `agent.py` at
its root, per `docs/submission_rules.md`, so this package exists purely so a harness
expecting the starter-kit path finds the same object rather than an ImportError.

Both names resolve to one implementation in `src/` -- there is no second copy.
"""

from src.agent import Agent

__all__ = ["Agent"]
'''

SHIM_INIT = '"""Compatibility shim for harnesses that import `starter.agent`."""\n'

# `starter/__init__.py` says "Participant starter package", which reads wrong in a bundle
# that has a `starter/` shim sitting next to this one. Give the implementation package its
# own line instead of inheriting the starter kit's.
SRC_INIT = (
    '"""Shopping Copilot agent implementation.\n\n'
    'The entry point is `agent.py` at the bundle root; this package holds the modules it\n'
    'orchestrates. Generated by `tools/build_submission.py` from the repository\'s\n'
    '`starter/` package -- the only difference is the import paths.\n"""\n'
)

# Things that must never reach a submission. `submission_rules.md` bars private
# evaluation data, copied organizer-only files, and secrets; the rest is hygiene.
FORBIDDEN_NAMES = (".env", "catalog.jsonl", "public_set.jsonl", "local_evaluator.py")
FORBIDDEN_SUFFIXES = (".pyc", ".pyo", ".jsonl", ".pdf")

# A key that escaped into the bundle is unrecoverable once submitted, so grep for the
# shape rather than trusting that nobody pasted one into a docstring.
SECRET_RE = re.compile(r"\bsk-(?:or-v1-)?[A-Za-z0-9]{20,}")


# The report carries a note telling a maintainer to edit it here rather than in the
# bundle. That instruction is meaningless to a judge reading the bundle, so it is fenced
# off and dropped on the way in.
STRIP_BLOCK = re.compile(
    r"<!-- build:strip-start -->.*?<!-- build:strip-end -->\n+", re.DOTALL
)


def strip_repo_only(text: str) -> str:
    return STRIP_BLOCK.sub("", text)


def rewrite_imports(source: str) -> str:
    for pattern, replacement in IMPORT_REWRITES:
        source = pattern.sub(replacement, source)
    return PATH_REWRITE.sub(r"src/\1.py", source)


def build() -> None:
    """Delete and regenerate `submission/` from `starter/`."""
    if BUNDLE.exists():
        shutil.rmtree(BUNDLE)
    (BUNDLE / "src").mkdir(parents=True)
    (BUNDLE / "starter").mkdir()

    for name in MODULES:
        source = (STARTER / name).read_text(encoding="utf-8")
        (BUNDLE / "src" / name).write_text(rewrite_imports(source), encoding="utf-8")
    (BUNDLE / "src" / "__init__.py").write_text(SRC_INIT, encoding="utf-8")

    (BUNDLE / "agent.py").write_text(ENTRY_POINT, encoding="utf-8")
    (BUNDLE / "starter" / "__init__.py").write_text(SHIM_INIT, encoding="utf-8")
    (BUNDLE / "starter" / "agent.py").write_text(SHIM, encoding="utf-8")

    shutil.copyfile(REPO / "requirements.txt", BUNDLE / "requirements.txt")
    for name, source in DOCUMENTS.items():
        if not source.exists():
            raise SystemExit(
                f"missing {source.relative_to(REPO)} -- it is the authored source of "
                f"submission/{name}, kept in docs/ so the bundle stays generated."
            )
        (BUNDLE / name).write_text(
            strip_repo_only(source.read_text(encoding="utf-8")), encoding="utf-8"
        )

    files = sorted(p.relative_to(BUNDLE).as_posix() for p in BUNDLE.rglob("*") if p.is_file())
    print(f"built submission/ -- {len(files)} files")
    for name in files:
        print(f"    {name}")


def check(label: str, ok: bool, detail: str = "") -> bool:
    print(f"  [{'PASS' if ok else 'FAIL'}] {label}" + (f" -- {detail}" if detail and not ok else ""))
    return ok


def verify_static() -> bool:
    """Everything that can be checked without running the evaluator."""
    results = []

    # Only the rewritten modules -- the shim and the report both name `starter.agent` on
    # purpose, in an import line and in prose respectively.
    leaked = [
        f"{p.relative_to(BUNDLE).as_posix()}:{i}"
        for p in sorted((BUNDLE / "src").rglob("*.py"))
        for i, line in enumerate(p.read_text(encoding="utf-8").splitlines(), 1)
        if re.match(r"\s*(from starter\b|import starter\b)", line)
    ]
    results.append(check(
        "no `starter` import survives in submission/src/",
        not leaked, ", ".join(leaked),
    ))

    # Line-count parity is what keeps the rewritten `src/file.py:NNN` cross-references in
    # the docstrings pointing at the lines they name. Every rewrite is within a line; this
    # asserts that stays true rather than trusting it.
    drifted = []
    for name in MODULES:
        if name == "__init__.py":
            continue  # deliberately replaced, not copied
        before = (STARTER / name).read_text(encoding="utf-8").count("\n")
        after = (BUNDLE / "src" / name).read_text(encoding="utf-8").count("\n")
        if before != after:
            drifted.append(f"{name} ({before} -> {after})")
    results.append(check(
        "rewriting preserved line counts, so `file.py:NNN` references stay accurate",
        not drifted, ", ".join(drifted),
    ))

    unparsed = []
    for path in BUNDLE.rglob("*.py"):
        try:
            ast.parse(path.read_text(encoding="utf-8"))
        except SyntaxError as exc:
            unparsed.append(f"{path.relative_to(BUNDLE)}: {exc}")
    results.append(check("every bundled .py parses", not unparsed, "; ".join(unparsed)))

    bad = [
        p.relative_to(BUNDLE).as_posix()
        for p in BUNDLE.rglob("*")
        if p.is_file() and (p.name in FORBIDDEN_NAMES or p.suffix in FORBIDDEN_SUFFIXES)
    ]
    results.append(check(
        "no data, organizer files, secrets file, or build artifacts in the bundle",
        not bad, ", ".join(bad),
    ))

    secrets = [
        p.relative_to(BUNDLE).as_posix()
        for p in BUNDLE.rglob("*")
        if p.is_file() and SECRET_RE.search(p.read_text(encoding="utf-8", errors="ignore"))
    ]
    results.append(check("no API-key-shaped string anywhere", not secrets, ", ".join(secrets)))

    expected = {"agent.py", "requirements.txt", *DOCUMENTS}
    present = {p.name for p in BUNDLE.iterdir() if p.is_file()}
    results.append(check(
        "required layout present (agent.py, requirements.txt, README.md, REPORT.md, src/)",
        expected <= present and (BUNDLE / "src" / "agent.py").exists(),
        f"missing {sorted(expected - present)}",
    ))

    # The maintainer note in each source is fenced off; a leaked marker means the fence
    # was edited into a shape `strip_repo_only` no longer matches.
    leaked_fence = [
        name for name in DOCUMENTS
        if "build:strip" in (BUNDLE / name).read_text(encoding="utf-8")
    ]
    results.append(check(
        "repo-only maintainer notes stripped from the bundled documents",
        not leaked_fence, ", ".join(leaked_fence),
    ))

    return all(results)


def verify_exports() -> bool:
    """Import the bundle in a clean subprocess and inspect the exported Agent.

    A subprocess, not an import here: this process already has `starter` loaded, and an
    in-process import would happily resolve against it and prove nothing.
    """
    probe = (
        "import sys; sys.path.insert(0, sys.argv[1]);"
        "import agent as m;"
        "assert hasattr(m, 'Agent'), 'agent.py does not export Agent';"
        "A = m.Agent;"
        "assert callable(getattr(A, 'reset', None)), 'Agent.reset missing';"
        "assert callable(getattr(A, 'respond', None)), 'Agent.respond missing';"
        "import starter.agent as s;"
        "assert s.Agent is A, 'the starter shim resolves to a different class';"
        "print('ok')"
    )
    result = subprocess.run(
        [interpreter(), "-c", probe, str(BUNDLE)],
        cwd=REPO, capture_output=True, text=True,
    )
    return check(
        "bundle exports Agent(reset, respond); starter shim is the same class",
        result.returncode == 0 and result.stdout.strip().endswith("ok"),
        (result.stderr.strip() or result.stdout.strip())[-300:],
    )


def interpreter() -> str:
    # `py` is the real launcher on the Windows dev machines; `python`/`python3` there hit
    # the Microsoft Store stub. Inside a virtualenv, the venv's own interpreter is right.
    return sys.executable if os.environ.get("VIRTUAL_ENV") else "py"


def verify_score() -> bool:
    """Run all 200 sessions against the bundle and require a byte-identical result.

    `PYTHONPATH` puts the bundle ahead of the repo, so `starter` resolves to the bundle's
    shim -- and therefore to `submission/src/agent.py`. `evaluator` still resolves from
    the repo root, which is what we want: the organizer's harness, our packaged agent.
    """
    if not REFERENCE.exists():
        return check("byte-identical to the score of record", False,
                     f"reference missing: {REFERENCE.relative_to(REPO)}")

    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join([str(BUNDLE), str(REPO), env.get("PYTHONPATH", "")])
    # The optional model must not be live during a verification run, or "byte-identical"
    # would be measuring the endpoint's mood rather than the bundle.
    env.pop("SHOPPING_COPILOT_LLM", None)
    env.pop("SILICONFLOW_LLM", None)

    with tempfile.TemporaryDirectory() as tmp:
        output = Path(tmp) / "bundle.json"
        print("  ... running 200 sessions against the bundle (~25-40 s)")
        result = subprocess.run(
            [interpreter(), "-m", "evaluator.local_evaluator", "--output", str(output)],
            cwd=REPO, env=env, capture_output=True, text=True,
        )
        if result.returncode != 0:
            print(result.stdout[-1500:])
            print(result.stderr[-1500:], file=sys.stderr)
            return check("byte-identical to the score of record", False, "evaluator failed")
        produced = output.read_text(encoding="utf-8")

    expected = REFERENCE.read_text(encoding="utf-8")
    if produced == expected:
        current = json.loads(produced)
        print(f"         TechnicalScore {current['recommended_technical_score']} "
              f"| HitRate {current['hit_rate_at_10']} | MRR {current['mrr']} "
              f"| MTTC {current['mttc']}")
        return check("byte-identical to the score of record", True)

    current = json.loads(produced)
    reference = json.loads(expected)
    moved = sum(1 for a, b in zip(current["sessions"], reference["sessions"]) if a != b)
    return check(
        "byte-identical to the score of record", False,
        f"{moved} sessions differ; score {current['recommended_technical_score']} "
        f"vs {reference['recommended_technical_score']}",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Build and verify the submission bundle.")
    parser.add_argument(
        "--skip-verify", action="store_true",
        help="build only -- for iterating; never for the bundle you actually submit",
    )
    args = parser.parse_args()

    build()

    if args.skip_verify:
        print("\nVerification skipped. Re-run without --skip-verify before submitting.")
        return 0

    print("\nverifying")
    ok = verify_static()
    ok = verify_exports() and ok
    ok = verify_score() and ok

    if ok:
        print("\nPASS: submission/ is the agent we measured, byte for byte.")
        return 0
    print("\nFAIL: do not submit this bundle until the checks above are green.")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
